export { default as Cart } from './cart'
export { default as Catalog } from './catalog'
export { default as Checkout } from './checkout'
export { default as Contact } from './contact'
export { default as Favorite } from './favorite'
export { default as Home } from './home'
export { default as Order } from './order'
export { default as ProductPage } from './product-page'
export { default as ServiceTerms } from './service-terms'

